- name: Obter lista de IPs da API e aplicar regras de mitigação
  hosts: localhost
  gather_facts: false
  vars:
    api_url: "http://164.72.15.30:5050/dados/ataques/novos"
    api_retries: 3
    target_ips: "{{ target_ips }}"
    flow_ids: "{{ flow_ids }}"
    access_token: "{{ access_token }}"
    inventory_file: "inventory.ini"

  tasks:
    - name: Verificar variáveis obrigatórias
      fail:
        msg: "As variáveis target_ips, flow_ids ou access_token não estão definidas."
      when: target_ips is not defined or flow_ids is not defined or access_token is not defined

    - name: Verificar variáveis recebidas
      debug:
        msg:
          - "target_ips: {{ target_ips }}"
          - "flow_ids: {{ flow_ids }}"
          - "access_token: {{ access_token }}"

    - name: Criar lista de IPs
      set_fact:
        ip_list: "{{ target_ips.split(',') }}"

    - name: Atualizar arquivo inventory.ini
      copy:
        content: |
          [Mirai_Bots]
          {% for ip in ip_list %}
          {{ ip }}
          {% endfor %}
        dest: "{{ inventory_file }}"
      register: inventory_update

    - name: Debug atualização do inventory
      debug:
        var: inventory_update

- name: Aplicar regras de mitigação nos hosts do inventory
  hosts: Mirai_Bots
  become: true
  vars:
    script_to_run: "block_https"
    dry_run: false

  tasks:
    - name: Testar conectividade SSH
      ping:
      register: ping_result

    - name: Debug resultado do ping
      debug:
        var: ping_result

    - name: Verificar existência do script block_https.sh
      stat:
        path: ./scripts/block_https.sh
      register: block_https_stat

    - name: Debug stat do script block_https.sh
      debug:
        var: block_https_stat

    - name: Block HTTPS
      script: ./scripts/block_https.sh
      register: resultado_block_https
      when: script_to_run == "block_https" and not dry_run

    - name: Resultado do script Block HTTPS
      debug:
        var: resultado_block_https

    - name: Log de execução
      debug:
        msg: "Execução concluída para o host {{ inventory_hostname }}"
      when: not dry_run