- hosts: Workstations
  become: true
  tasks:
    - name: Block ssh
      command: /scripts/block_ssh.sh
      register: resultado

    - name: Resultado do script
      debug:
        var: resultado.stdout
